trigger:
- master

pool:
  name: Default
  demands:
    - Agent.Name -equals ThinkpadE14

variables:
  - group: Tokens  # Replace with your actual variable group name
  - group: Email_Secrets


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
  env:
    AZURE_PAT: $(AZURE_PAT)  # Inject the secret as an environment variable

- script: |
    echo "Copying HTML report to artifact staging directory"
    copy "reports\index.html" "$(Build.ArtifactStagingDirectory)\index.html"
  displayName: 'Copy HTML Report'
  condition: always()


- task: SendEmail@1
  condition: always()
  inputs:
    To: 'nsr.kpma@outlook.com'
    From: 'nsr01734@gmail.com'
    Subject: 'Selenium Test Automation Report'
    Body: |
      Hi Team,
      Please find the Selenium test automation report in the attachments.
      Also Please Check the Azure Test Plan results for detailed results and tracability.
      Thanks
      Nirmal
    BodyAsHtml: false
    AddAttachment: true
    Attachment: '$(Build.ArtifactStagingDirectory)/index.html'
    SmtpServer: 'smtp.gmail.com'
    SmtpUsername: '$(SMTP_USER_NAME)'
    SmtpPassword: '$(SMTP_PASSWORD)'